[project]
name = "witcher3-save-edit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chardet>=5.2.0",
    "lz4>=4.4.4",
]
